#!/usr/bin/env python

import torch

if torch.cuda.is_available():
    from app import Model

    model = Model()

    model.setup()

    model.warmup()
else:
    print("[WARNING] CUDA not available, skipping warmup")
